param([string]$ProjectRoot = (Join-Path $PSScriptRoot '../..'))

$ErrorActionPreference = 'Stop'
$projectPath = (Resolve-Path -LiteralPath $ProjectRoot).Path
$mainRoot = Join-Path $projectPath 'src/main/java'
$testRoot = Join-Path $projectPath 'src/test/java'
$issues = [System.Collections.Generic.List[string]]::new()
$sourcePaths = @{}
$javaCount = 0
$importCount = 0
$mixinCount = 0
$reservedMixinTypeCount = 0
$qaPathCount = 0

function Test-ProjectType([string]$TypeName) {
    $candidate = $TypeName
    while ($candidate.StartsWith('com.xyp.gtnotgood.')) {
        if ($sourcePaths.ContainsKey($candidate)) { return $true }
        $candidate = $candidate.Substring(0, $candidate.LastIndexOf('.'))
    }
    return $false
}

$mainFiles = @(Get-ChildItem -LiteralPath $mainRoot -Recurse -File -Filter '*.java')
foreach ($sourceRoot in @($mainRoot, $testRoot)) {
    if (-not (Test-Path -LiteralPath $sourceRoot)) { continue }
    foreach ($file in Get-ChildItem -LiteralPath $sourceRoot -Recurse -File -Filter '*.java') {
        $relative = $file.FullName.Substring($sourceRoot.Length + 1).Replace('\', '/')
        $type = $relative.Substring(0, $relative.Length - 5).Replace('/', '.')
        $sourcePaths[$type] = $true
    }
}
# Tags is generated by the GTNH Gradle convention rather than stored in src/main.
$sourcePaths['com.xyp.gtnotgood.Tags'] = $true

foreach ($sourceRoot in @($mainRoot, $testRoot)) {
    if (-not (Test-Path -LiteralPath $sourceRoot)) { continue }
    foreach ($file in Get-ChildItem -LiteralPath $sourceRoot -Recurse -File -Filter '*.java') {
        $javaCount++
        $content = Get-Content -LiteralPath $file.FullName -Raw -Encoding UTF8
        $relative = $file.FullName.Substring($sourceRoot.Length + 1).Replace('\', '/')
        $expectedPackage = $relative.Substring(0, $relative.LastIndexOf('/')).Replace('/', '.')
        $package = [regex]::Match($content, '(?m)^package ([\w.]+);')
        if (-not $package.Success -or $package.Groups[1].Value -cne $expectedPackage) {
            $issues.Add("Package/path mismatch: $relative")
        }
        foreach ($import in [regex]::Matches($content, '(?m)^import (?:static )?(com\.xyp\.gtnotgood\.[\w.]+);')) {
            $importCount++
            if (-not (Test-ProjectType $import.Groups[1].Value)) {
                $issues.Add("Missing project import: $relative -> $($import.Groups[1].Value)")
            }
        }
        if ($sourceRoot -ne $mainRoot -or $expectedPackage -notlike 'com.xyp.gtnotgood.common.*') { continue }
        if ($content -match '\bclass \w+ extends (?:ItemBlock|GTNGItemBlock)\b') {
            if ($expectedPackage -notlike 'com.xyp.gtnotgood.common.blocks*') { $issues.Add("ItemBlock outside blocks: $relative") }
        } elseif ($content -match '\bclass \w+ extends (?:Item|GTNGItem|ItemPickaxe|ItemEncodedPattern|ItemRadioactiveCellIC)\b') {
            if ($expectedPackage -notlike 'com.xyp.gtnotgood.common.items*') { $issues.Add("Item outside items: $relative") }
        } elseif ($content -match '\bclass \w+ extends Block\b') {
            if ($expectedPackage -notlike 'com.xyp.gtnotgood.common.blocks*') { $issues.Add("Block outside blocks: $relative") }
        }
    }
}

$resources = Join-Path $projectPath 'src/main/resources'
$mixinPackages = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::Ordinal)
$mixinPlugins = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::Ordinal)
foreach ($file in Get-ChildItem -LiteralPath $resources -File -Filter 'mixins*.json') {
    $config = Get-Content -LiteralPath $file.FullName -Raw -Encoding UTF8 | ConvertFrom-Json
    if ($config.package) { [void]$mixinPackages.Add($config.package) }
    if ($config.plugin) { [void]$mixinPlugins.Add($config.plugin) }
    foreach ($entry in @($config.mixins) + @($config.client) + @($config.server)) {
        $mixinCount++
        if (-not (Test-ProjectType "$($config.package).$entry")) { $issues.Add("Missing configured mixin: $entry") }
    }
}
# Mixin excludes every class below its configured package from normal class loading, including unlisted helpers.
foreach ($file in $mainFiles) {
    $content = Get-Content -LiteralPath $file.FullName -Raw -Encoding UTF8
    $package = [regex]::Match($content, '(?m)^package ([\w.]+);').Groups[1].Value
    $reserved = $false
    foreach ($prefix in $mixinPackages) {
        if ($package -ceq $prefix -or $package.StartsWith($prefix + '.', [System.StringComparison]::Ordinal)) {
            $reserved = $true
            break
        }
    }
    if (-not $reserved) { continue }
    $code = [regex]::Replace($content, '(?s)/\*.*?\*/|//[^\r\n]*|"(?:\\.|[^"\\])*"|''(?:\\.|[^''\\])*''', {
        param($match)
        $match.Value -replace '[^\r\n]', ' '
    })
    $depth = 0
    $parentheses = 0
    $isMixin = $false
    $tokens = [regex]::Matches($code, '(?<mixin>@\s*(?:[\w$]+\s*\.\s*)*Mixin\b)|(?<kind>@interface|\b(?:class|interface|enum|record))\s+(?<name>[A-Za-z_$][\w$]*)|(?<delimiter>[{}();])')
    foreach ($token in $tokens) {
        if ($token.Groups['mixin'].Success) {
            if ($depth -eq 0 -and $parentheses -eq 0) { $isMixin = $true }
        } elseif ($token.Groups['name'].Success) {
            if ($depth -ne 0 -or $parentheses -ne 0) { continue }
            $reservedMixinTypeCount++
            $type = $package + '.' + $token.Groups['name'].Value
            if (-not $isMixin -and -not $mixinPlugins.Contains($type)) {
                $issues.Add("Ordinary type in reserved mixin package: $type (move runtime helpers outside $package)")
            }
            $isMixin = $false
        } else {
            switch ($token.Value) {
                '(' { $parentheses++ }
                ')' { $parentheses-- }
                '{' { if ($parentheses -eq 0) { $depth++ } }
                '}' {
                    if ($parentheses -eq 0) {
                        $depth--
                        if ($depth -eq 0) { $isMixin = $false }
                    }
                }
                ';' { if ($depth -eq 0 -and $parentheses -eq 0) { $isMixin = $false } }
            }
        }
    }
}
$loader = Get-Content -LiteralPath (Join-Path $mainRoot 'com/xyp/gtnotgood/loader/LateMixinsLoader.java') -Raw -Encoding UTF8
foreach ($entry in [regex]::Matches($loader, '"([a-z][a-z0-9]*(?:\.[a-z][a-z0-9]*)*\.[A-Z][A-Za-z0-9_$]*)"')) {
    $mixinCount++
    $type = 'com.xyp.gtnotgood.mixins.late.' + $entry.Groups[1].Value
    if (-not (Test-ProjectType $type)) { $issues.Add("Missing late mixin: $type") }
}

$relativeMainFiles = @($mainFiles | ForEach-Object { $_.FullName.Substring($projectPath.Length + 1).Replace('\', '/') })
foreach ($file in Get-ChildItem -LiteralPath (Join-Path $projectPath 'scripts') -File -Filter '*.init.gradle') {
    $content = Get-Content -LiteralPath $file.FullName -Raw -Encoding UTF8
    foreach ($match in [regex]::Matches($content, "['`"](src/main/java/[^'`"]+)['`"]")) {
        $qaPathCount++
        $pattern = '^' + [regex]::Escape($match.Groups[1].Value).Replace('\*', '.*').Replace('\?', '.') + '$'
        if (-not ($relativeMainFiles -cmatch $pattern) -and -not (Test-Path -LiteralPath (Join-Path $projectPath $match.Groups[1].Value) -PathType Container)) {
            $issues.Add("Missing QA source path: $($file.Name) -> $($match.Groups[1].Value)")
        }
    }
}

if ($issues.Count -gt 0) { throw ($issues -join [Environment]::NewLine) }
Write-Output "PASS: $javaCount Java locations, $importCount project imports, $mixinCount mixins, $reservedMixinTypeCount reserved mixin types, $qaPathCount QA source paths."
